server:
  port: 4080
spring:
  application:
    name: document-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: multiservice
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: '2'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: document-service
        hbm2ddl:
          create_namespaces: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

minio:
  url: http://localhost:9000
  access-key: myaccesskey
  secret-key: mysecretkey